### ISSUE TITLE
Would it be within the scope of mason/mason-registry to add pylsp plugins?

### ISSUE THREAD

**Issue by IndianBoy42** [mason-org/mason-registry#2241]
Ref: https://github.com/python-lsp/python-lsp-server#3rd-party-plugins

These third party plugins have to be installed manually for now

**Comment by IndianBoy42** [comment]
Hmm actually, after trying to add it as a local custom registry I see a problem in that these extensions have to be installed into the same venv as `python-lsp-server`. Does mason have a way to do this kind of injection?

**Comment by brandoncc** [comment]
I'm looking for the same thing, I'd like to install `stylelint-config-standard` within the context of `stylelint_lsp`.

**Comment by williamboman** [comment]
Hello! Yep, see https://github.com/williamboman/mason.nvim/issues/392. Aiming to add support in the upcoming 2.0.0 release.
