### ISSUE TITLE
no matching distribution found for debugpy==1.6.8

### ISSUE THREAD

**Issue by leileimi** [mason-org/mason-registry#2381]
when install debugpy ,error occurs 
ERROR: Could not find a version that satisfies the requirement debugpy==1.6.8 (from versions: 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5, 1.0.0b6, 1.0.0b7, 1.0.0b8, 1.0.0b9, 1.0.0b10, 1.0.0b11, 1.0.0b12, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.2.post1, 1.4.3, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7)
        ERROR: No matching distribution found for debugpy==1.6.8
        spawn: /home/leiming/.local/share/lvim/mason/packages/debugpy/venv/bin/python failed with exit code 1 and signal 0.

**Comment by MrGreenTea** [comment]
I've created a PR to revert the update #2344 

Until it get's merged you can do  `:MasonInstall debugpy@1.6.7` as a workaround and it should work (or at the least it did for me)
