### ISSUE TITLE
The current platform is unsupported

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [mason-org/mason-registry#2490]
good morning,

**the context**: I have recently installed neovim ( v0.9.1; LuaJIT 2.1.0-beta3 ) on FreeBSD 13.2

**the problem**: it seems that I cannot install a couple of language servers using Mason, e.g. lua-language-server, zls language server. Installation request does always fail with the "The current platform is unsupported".

Could you please guide me how to fix this ( if it is at all fixable, of course )?

**PS**: I am not quite sure if this is the right place to ask this question. If it is not, please let me know and I will close this isue.

**Comment by williamboman** [comment]
Hello! Some packages provide binaries linked to glibc, in which case installation will fail with that message if you're on a system without glibc (FreeBSD for example). If you have glibc installed but installation fails you can specify the target explicitly, like so: `:MasonInstall --target=linux_x64_gnu zls`.
