### ISSUE TITLE
Support npm:@biomejs/biome replacement for npm:rome

### ISSUE THREAD

**Issue by zapling** [mason-org/mason-registry#2600]
Hey,

The guys working on the `rome` project has decided to fork and will now be maintaining the project under a different name `biome`. There is an open PR to add support for biome in lspconfig but it has not been merged yet. I assume we want to wait until that is merged, but I wanted to raise a ticket here beforehand.

https://github.com/neovim/nvim-lspconfig/pull/2790
https://biomejs.dev/blog/annoucing-biome

**Comment by chrisgrieser** [comment]
In fact, I have also opened a PR for the mason-registry as well ;)
#2601

**Comment by zapling** [comment]
> In fact, I have also opened a PR for the mason-registry as well ;) #2601

I missed that :joy:, closed my PR I just opened :joy:

**Comment by zapling** [comment]
Fixed as per #2601
