### ISSUE TITLE
ZLS released version 0.12

### ISSUE THREAD

**Issue by adworacz** [mason-org/mason-registry#5504]
https://github.com/zigtools/zls/releases/tag/0.12.0

Current version in this repo is 0.11.

**Comment by qazo** [comment]
should be updated in #5500. could you check and confirm from your side?
here's my result on mason
![image](https://github.com/mason-org/mason-registry/assets/2219870/c9e10e49-8c35-48fe-bcc1-ca5381ef9e87)

**Comment by adworacz** [comment]
Yup - I confirm that this is updated. Thank you!
