### ISSUE TITLE
Lua-language-server does not support target `linux_arm64_gnu`

### ISSUE THREAD

**Issue by sfc-gh-mjendruk** [mason-org/mason-registry#5765]
Hello,

recently the `linux_arm64_gnu` target was removed for the lua-language-server. This was probably because release 3.8.3 didn't contain the binaries for it.
https://github.com/mason-org/mason-registry/commit/236670a1fc884e3de487428f1cce9fa3447e9610

For the latest release 3.9.1, the binaries are however available again. Can we add the `linux_arm64_gnu` target again?

**Comment by Conarius** [comment]
Was done in #5696, can be closed now
