### ISSUE TITLE
add linux_arm64 to clangd registry

### ISSUE THREAD

**Issue by Elyasb14** [mason-org/mason-registry#5800]
Hi, I am trying to run `:MasonInstall clangd` inside neovim on a raspberry pi 5. However, it seems like you all don't have the linux_arm64 in the clangd registry.

**Comment by Moerliy** [comment]
+1

**Comment by IronBlood** [comment]
There was a pull request #1635

The problem is there's no prebuilt clangd for linux_arm64 here https://github.com/clangd/clangd/releases

I have a temporary workaround:

```bash
sudo apt install clangd-16
ln -s /usr/bin/clangd-16 ~/.local/share/nvim/mason/bin/clangd
mkdir ~/.local/share/nvim/mason/packages/clangd
```

It works on my RPi 4.

**Comment by Moerliy** [comment]
Yeah, I dug a bit deeper and I'm not sure if this will get resolved anytime soon. There is an issue open in clangd's repo it stayed the same for 2 Years or so.
When you are already downloading the bin with your package manager you could just not use mason for clangd at all. 
Plugins like `nvim-lspconfig` will fall back to your `PATH` and search for clangd's bin directly if you disable mason.

What I have done:
Get clangd with system package manager, 
```lua
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        clangd = {
          mason = false,
        },
      },
    },
  },

```
and get ridge of clangd in your `ensure_installed` in your mason's conf.

Note: Not sure if this is the best way but I'm leaving this here so whoever stumbles upon it can decide for themselves.

**Comment by Elyasb14** [comment]
Thanks for all your responses here. These all seem like very reasonable workarounds. Going to close this issue with thanks.

**Comment by rohit-kumar-j** [comment]
> Yeah, I dug a bit deeper and I'm not sure if this will get resolved anytime soon. There is an issue open in clangd's repo it stayed the same for 2 Years or so. When you are already downloading the bin with your package manager you could just not use mason for clangd at all. Plugins like `nvim-lspconfig` will fall back to your `PATH` and search for clangd's bin directly if you disable mason.
> 
> What I have done: Get clangd with system package manager,
> 
> ```lua
>   {
>     "neovim/nvim-lspconfig",
>     opts = {
>       servers = {
>         clangd = {
>           mason = false,
>         },
>       },
>     },
>   },
> ```
> 
> and get ridge of clangd in your `ensure_installed` in your mason's conf.
> 
> Note: Not sure if this is the best way but I'm leaving this here so whoever stumbles upon it can decide for themselves.

Thank you so much! getting rid of **ensure_installed** in mason config saved the day on my Apple Asahi Linux M2 arm machine!

**Comment by mufeedcm** [comment]
> sudo apt install clangd-16
> ln -s /usr/bin/clangd-16 ~/.local/share/nvim/mason/bin/clangd
> mkdir ~/.local/share/nvim/mason/packages/clangd
> 
> It works on my RPi 4.

to add to this, that will be diff based on the package manager and all, 

so after installing clangd with the specific package manager u guys use, 

first create the folders,
```bash
  mkdir -p ~/.local/share/nvim/mason/bin
  mkdir -p ~/.local/share/nvim/mason/packages/clangd
````
then run,

` which clangd` u will get a result like ,

<img width="262" height="108" alt="Image" src="https://github.com/user-attachments/assets/2f7931a4-ca0d-4d20-b284-3f57b5552fba" />

change the command based on that, this will link the folder, 
 
  `ln -sf /usr/bin/clangd ~/.local/share/nvim/mason/bin/clangd`



btw i have to mention that this is not the best way, but this was the way i got it fixed for now,
