### ISSUE TITLE
Meson Build System

### ISSUE THREAD

**Issue by mkohlhaas** [mason-org/mason-registry#5864]
MesonLsp cannot find `root directory`.
Should be directory of  `meson.build` file.

```
 Detected filetype:   meson
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: meson
 
 Config: mesonlsp
 	filetypes:         meson
 	root directory:    Not found.
 	cmd:               /home/kohlhaas/.local/share/nvim/mason/bin/mesonlsp --lsp
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
```

**Comment by Conarius** [comment]
I think this is more of an issue with nvim-lspconfig as the mason registry just installs and links the package.

**Comment by mkohlhaas** [comment]
I'm a bit confused. I thought `mason` would handle all the default configurations.

Here is the [LSP server config for meson](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/mesonlsp.lua).

**Comment by Conarius** [comment]
Yeah, mason really just installs the package and links them so nvim-lspconfig can use them.
I do think at this point you should ask over on nvim-lspconfig for help.
